version: '3.3'

services:
  request-logger:
    image: andboson/http-cli-echo-logger
    ports:
      - "8081:8080"
    environment:
      CUSTOM_ENDPOINTS: |-
        /api/v1/echo
        /api/v2/echo
        /api/v1/mock::{"foo":"bar"}