version: '3.3'

services:
  request-logger:
    build: .
    ports:
      - "8081:80"
    environment:
      CUSTOM_ENDPOINTS: |-
              [
                {
                  "path":"/graphQl",
                  "request":"{\"foo1\":\"bar\"}",
                  "mock":"{\"foo_resp1\":\"bar_resp1\"}"
                },
                {
                  "path":"/graphQl",
                  "request":"{\"foo2\":\"bar\"}",
                  "mock":"{\"foo_resp2\":\"bar_resp2\"}"
                },
                {
                  "path":"/auth",
                  "request":"",
                  "mock":"{\"key\":\"auth_key\"}"
                }
              ]
